Solution
mate-academy/py-cat-and-dog-years pull request #207
Opened 2022-11-23 15:56 UTC by mish-sk

2022-11-24 09:11 UTC, Abnormaltype requested changes
use checklist

2022-11-29 09:52 UTC, Serhii-Leonenko requested changes
Add more tests for all use cases, like an example test that 15 cat and dog years gives 1 year, but values lower than 15 like 14 - no, etc
![image](https://user-images.githubusercontent.com/104218550/204496256-d5793aee-1504-4cae-a022-1c0eb606190f.png)

2022-11-29 09:52 UTC, Serhii-Leonenko commented on app/test_main.py
> +def test_get_human_age() -> None:
It's not a good descriptive  name for test

2022-11-30 13:01 UTC, OleksandrPozden commented on app/test_main.py
> +    assert result_1 is not result_2
You can write in simpler in one row

2022-12-01 15:59 UTC, IvanRamyk requested changes

2022-12-01 15:59 UTC, IvanRamyk commented on app/test_main.py
> +    assert get_human_age(30, 33) is not get_human_age(30, 33)
don't understand what do you want to check here

2022-12-06 13:35 UTC, OleksandrPozden approved these changes

2024-03-11 09:39 UTC, closed without merging