solution
mate-academy/py-cat-and-dog-years pull request #417
Opened 2023-05-26 13:38 UTC by sbilikepy

2023-05-26 18:17 UTC, vsmutok requested changes
add tests for incorrect types

2023-05-26 18:21 UTC, sbilikepy commented
> add tests for incorrect types
```
def test_numeric_values_in_returned_list() -> None:
    for age in get_human_age(15, 15.0):
        assert isinstance(age, (int, float))
```
should i change it? If yes - вo I need to add a function argument check for all types except `int` and `float`?

2023-05-27 14:59 UTC, YukihiroSM requested changes
It's not really about handling -> that means, that the function throws an exception. Try to check, that the function really throws an exception in case of wrong types of input data. 
Try takin a look into with pytest.raises

2023-05-27 15:30 UTC, sbilikepy commented
![image](https://github.com/mate-academy/py-cat-and-dog-years/assets/109094572/ada2edcb-6d14-4e6b-ac00-fdacb9eac4de)

2023-05-27 17:30 UTC, Bohdan-Salamakha approved these changes

2023-05-30 03:20 UTC, sbilikepy commented
Approve it again if solution is correct please
![image](https://github.com/mate-academy/py-cat-and-dog-years/assets/109094572/0d6ed245-fc6c-46fb-806b-d72d051f647b)

2023-05-30 07:46 UTC, Abnormaltype approved these changes

2026-07-30 15:20 UTC, closed without merging