solution
mate-academy/py-cat-and-dog-years pull request #451
Opened 2023-06-14 10:03 UTC by mariiahorbova

2023-06-14 12:09 UTC, IhorVoskoboinikov commented on app/test_main.py
> +)
For better readability, you need to add an "id" with a description of the check. Example:
pytest.param(0, 0, [0, 0], id="both ages zero") or add ids=[<test description 1>, <test description 2>.......]

2023-06-14 12:11 UTC, IhorVoskoboinikov requested changes
Add test description for better readability (id)

2023-06-14 12:30 UTC, IhorVoskoboinikov approved these changes

2023-06-14 14:17 UTC, YuriiKindrat requested changes

2023-06-14 14:17 UTC, YuriiKindrat commented on app/test_main.py
> +        (28, 28, [3, 2])
what about big/negative numbers ?
![image](https://github.com/mate-academy/py-cat-and-dog-years/assets/103201010/704ca845-9dcb-4102-b9ae-0658056e13b9)

2023-06-15 09:17 UTC, YuriiKindrat approved these changes

2024-03-13 20:01 UTC, closed without merging