solution
mate-academy/py-cat-and-dog-years pull request #562
Opened 2023-08-28 13:53 UTC by ivanzh13

2023-08-28 14:04 UTC, ivanzh13 commented
I don't understand what I should do. No function throws an error. How am I supposed to test something that doesn't exist?

2023-08-28 15:53 UTC, vsmutok requested changes

2023-08-28 15:53 UTC, vsmutok commented on app/test_main.py
> +        (100, 100, [21, 17])
add a test that will check for invalid data types, for example `"14"`

2023-08-29 08:30 UTC, ArsenPidhoretskyi requested changes

2023-08-29 08:30 UTC, ArsenPidhoretskyi commented on app/test_main.py
> +        assert get_human_age("14", "14") == [0, 0]
Also for example if it accepts [14], [14]
Will be also nice test

2023-08-29 10:03 UTC, ArsenPidhoretskyi approved these changes
Well done!

2023-09-18 16:12 UTC, closed without merging